# Represents entries in the brain, i.e. the blackboard of the agent.
DIBI_SPEAKER = "Dibi/Speaker"
DIBI_CORPUS = "Dibi/Corpus"
DIBI_DIALOG = "Dibi/Dialog"
DIBI_CAMERA = "Dibi/Camera"
DIBI_GAMEREGION = "Dibi/GameRegion"
DIBI_POSEESTIMATION = "Dibi/PoseEstimation"
DIBI_BODY = "Dibi/Body"
DIBI_FACEDETECTOR = "Dibi/FaceDetector"
DIBI_OPPONENTNAME = "Dibi/OpponentName"
DIBI_ACTIVEGAME = "Dibi/ActiveGame"
DIBI_NAMEREACTION = "Dibi/NameReaction"
DIBI_ASYNCSERVICE = "Dibi/AsyncService"
DIBI_MOODDETECTOR = "Dibi/MoodDetector"
DIBI_LED = "Dibi/LED"